In [32]:
import sys

In [33]:
print(sys.version)

3.11.9 | packaged by Anaconda, Inc. | (main, Apr 19 2024, 16:40:41) [MSC v.1916 64 bit (AMD64)]


# Python practice
* [Task 1](#Null-bullet)
* [Task 2](#second-bullet)

## Task 1 <a class="anchor" id="Null-bullet"></a>
## Data types

### Int, float and str

In [3]:
x = 9
x

9

In [4]:
type(x)

int

In [5]:
y = 9.5
type(y)

float

In [6]:
z = float(x)
type(z)

float

In [7]:
z

9.0

In [8]:
a = int(y)
a

9

In [9]:
str = "hello world"
str

'hello world'

In [10]:
len(str)

11

In [11]:
# slicing
str[1:]

'ello world'

In [12]:
str[::-1]

'dlrow olleh'

In [13]:
str[2:9:2]

'lowr'

In [14]:
str.upper()

'HELLO WORLD'

In [15]:
str.title()

'Hello World'

In [16]:
str.startswith("a")

False

In [17]:
str.endswith("d")

True

In [18]:
str.split()

['hello', 'world']

In [19]:
str2 = "hello-to-you"
str2.split("-")

['hello', 'to', 'you']

In [20]:
" ".join(["hello","world","cs"])

'hello world cs'

In [21]:
nums = "68492"
sorted(nums)

['2', '4', '6', '8', '9']

In [22]:
# format
n= 19
m= 11
print("hello {} the {}".format(n,m))

hello 19 the 11


In [55]:
'x' in 'ahmed'

False

### Lists

In [23]:
list1 = [1,2,"yara",["haha","try","skyfall"]]
list1

[1, 2, 'yara', ['haha', 'try', 'skyfall']]

In [24]:
list1[2]

'yara'

In [25]:
list1[3][2]

'skyfall'

In [26]:
list1[3][2][5]

'l'

In [27]:
list1.append("well")
list1

[1, 2, 'yara', ['haha', 'try', 'skyfall'], 'well']

In [28]:
list1 + ["ok","see"]

[1, 2, 'yara', ['haha', 'try', 'skyfall'], 'well', 'ok', 'see']

In [29]:
len(list1)

5

In [30]:
list1.insert(2,"ins")
list1

[1, 2, 'ins', 'yara', ['haha', 'try', 'skyfall'], 'well']

In [31]:
list1.remove("yara")
list1

[1, 2, 'ins', ['haha', 'try', 'skyfall'], 'well']

In [32]:
del list1[4:]
list1

[1, 2, 'ins', ['haha', 'try', 'skyfall']]

In [33]:
list1.reverse()
list1

[['haha', 'try', 'skyfall'], 'ins', 2, 1]

### Sets

In [1]:
set1 = {1,2,3,4}

In [2]:
# convert from list to set
list1 = [1,1,2,2,3,4,5,6,1,1]
x = set(list1)
x

{1, 2, 3, 4, 5, 6}

In [3]:
set1.add(7)

In [4]:
set1

{1, 2, 3, 4, 7}

In [5]:
set1.discard(2)
set1

{1, 3, 4, 7}

In [6]:
set1[1] # not indexed

TypeError: 'set' object is not subscriptable

In [7]:
for i in set1:
    print(2*i)

2
6
8
14


### Tuples

In [9]:
tup = (1,2,3,4)
tup

(1, 2, 3, 4)

In [10]:
tup[1]

2

In [11]:
tup.index(4)

3

In [12]:
tup[0] = 'change' # immutable

TypeError: 'tuple' object does not support item assignment

In [13]:
for i in tup:
    print(2*i)

2
4
6
8


# If-else statements

In [44]:
x = False
if x:
    print('x was True!')
else:
    print('finish')

finish


In [45]:
x = 10
y = 5
print("Choose an OP")
op = input()

if op == '+':
    print(f"the sum for {x} + {y} = {x + y}")
elif op == '-':
    print(f"the subtraction for {x} - {y} = {x - y}")
elif op == '*':
    print(f"the multpling for {x} * {y} = {x * y}")
elif op == '/':
    print(f"the division for {x} / {y} = {x / y}")
else:
    print('wrong operation')

Choose an OP

wrong operation


# For and while loops

In [46]:
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for n in list1:
    print(n)

10
20
30
40
50
60
70
80
90
100


In [47]:
list1 = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
for n in range(1,len(list1)):
    print(list1[n])

20
30
40
50
60
70
80
90
100


In [48]:
for n in list1:
    if n == 50:
        break
    else:
        print(n)

10
20
30
40


In [49]:
for n in list1:
    if n == 50:
        continue
    else:
        print(n)

10
20
30
40
60
70
80
90
100


In [50]:
counter = 0
while counter <= 10:
    print(counter)
    counter = counter + 1
else:
    print("else")

0
1
2
3
4
5
6
7
8
9
10
else


In [51]:
counter = 0
while counter <= 10:
    print(counter)
    if counter == 6:
        print("breaking")
        break
    counter = counter + 1
else:
    print("else")

0
1
2
3
4
5
6
breaking


In [52]:
x = 0
while x < 10:
    x += 1
    print(x)
    if x == 7:
        print('breaking')
        break
    elif x == 3:
        print('continuing')
        continue
    print('nice')

1
nice
2
nice
3
continuing
4
nice
5
nice
6
nice
7
breaking


In [53]:
list(enumerate('abcde', 8))

[(8, 'a'), (9, 'b'), (10, 'c'), (11, 'd'), (12, 'e')]

In [54]:
for idx, letter in enumerate('abcde'):
    print(f'at index {idx} charchter is {letter}')

at index 0 charchter is a
at index 1 charchter is b
at index 2 charchter is c
at index 3 charchter is d
at index 4 charchter is e


# Functions

In [56]:
def sayMeow():
    print("meow")
sayMeow()

meow


In [58]:
def calc(x,y,op):
    if op == '+':
        print(f"the sum for {x} + {y} = {x + y}")
    elif op == '-':
        print(f"the subtraction for {x} - {y} = {x - y}")
    elif op == '*':
        print(f"the multpling for {x} * {y} = {x * y}")
    elif op == '/':
        print(f"the division for {x} / {y} = {x / y}")
    else:
        print('wrong operation')
calc(5,6,"+")

the sum for 5 + 6 = 11


In [59]:
calc(5,6,"-")

the subtraction for 5 - 6 = -1


In [60]:
# lambda exp
lambda num: num ** 2

<function __main__.<lambda>(num)>

In [61]:
my_nums = [1,2,3,4,5]
list(map(lambda num: num ** 2, my_nums))

[1, 4, 9, 16, 25]

# Task 2 <a class="anchor" id="second-bullet"></a>

### Dictionaries

In [14]:
dict1 = {'key1': 123, 'key2': [22, 23, 33], 'key3': ['item0','item1','item2'], 'key4': {'a': 30, 'b':40}}
type(dict1)

dict

In [21]:
# access value
print(dict1["key1"])
print(dict1["key2"])
print(dict1["key2"][2])
print(dict1["key3"][2].upper())

123
[22, 23, 33]
33
ITEM2


In [22]:
del dict1['key3'][2]
dict1

{'key1': 123,
 'key2': [22, 23, 33],
 'key3': ['item0', 'item1'],
 'key4': {'a': 30, 'b': 40}}

In [23]:
# insert 
dict1['key4'] = "data science"
dict1

{'key1': 123,
 'key2': [22, 23, 33],
 'key3': ['item0', 'item1'],
 'key4': 'data science'}

In [25]:
# update 
dict1['key2'][2] = 55
dict1

{'key1': 123,
 'key2': [22, 23, 55],
 'key3': ['item0', 'item1'],
 'key4': 'data science'}

In [30]:
for key, index in dict1.items():
    print("Key is "+ key + "Values are "+ str(index))

Key is key1Values are 123
Key is key2Values are [22, 23, 55]
Key is key3Values are ['item0', 'item1']
Key is key4Values are data science


## Dataframe

In [83]:
pip install pandas

   ---------------------------------------- 0.0/11.6 MB ? eta -:--:--
    --------------------------------------- 0.3/11.6 MB ? eta -:--:--
   --- ------------------------------------ 1.0/11.6 MB 3.6 MB/s eta 0:00:03
   ------- -------------------------------- 2.1/11.6 MB 3.8 MB/s eta 0:00:03
   --------- ------------------------------ 2.9/11.6 MB 3.9 MB/s eta 0:00:03
   ------------ --------------------------- 3.7/11.6 MB 3.9 MB/s eta 0:00:03
   --------------- ------------------------ 4.5/11.6 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 5.2/11.6 MB 3.9 MB/s eta 0:00:02
   -------------------- ------------------- 6.0/11.6 MB 3.9 MB/s eta 0:00:02
   --------------------- ------------------ 6.3/11.6 MB 3.9 MB/s eta 0:00:02
   ----------------------- ---------------- 6.8/11.6 MB 3.6 MB/s eta 0:00:02
   --------------------------- ------------ 7.9/11.6 MB 3.7 MB/s eta 0:00:02
   ---------------------------- ----------- 8.4/11.6 MB 3.7 MB/s eta 0:00:01
   ----------

In [2]:
import pandas as pd

data = {
  "calories": [420, 380, 390],
  "duration": [50, 40, 45]
}

df = pd.DataFrame(data)
print(df) 

   calories  duration
0       420        50
1       380        40
2       390        45


In [86]:
df = pd.DataFrame(data, index = ["day1", "day2", "day3"])
df

calories  duration
day1       420        50
day2       380        40
day3       390        45

In [87]:
data = np.array([(1, 2, 3), (4, 5, 6), (7, 8, 9)], dtype=[("a", "i4"), ("b", "i4"), ("c", "i4")])
df3 = pd.DataFrame(data, columns=['c', 'a'])
df3

c  a
0  3  1
1  6  4
2  9  7

In [3]:
weather_data = {
    'day': ['1/1/2024','1/2/2024','1/3/2024','1/4/2024','1/5/2024','1/6/2024'],
    'temperature': [32,35,28,24,32,31],
    'windspeed': [6,7,2,7,4,2],
    'event': ['Rain', 'Sunny', 'Snow','Snow','Rain', 'Sunny']
}
df = pd.DataFrame(weather_data)
df.to_csv('weather_data.csv', index=False)
df = pd.read_csv("weather_data.csv")
df

day  temperature  windspeed  event
0  1/1/2024           32          6   Rain
1  1/2/2024           35          7  Sunny
2  1/3/2024           28          2   Snow
3  1/4/2024           24          7   Snow
4  1/5/2024           32          4   Rain
5  1/6/2024           31          2  Sunny

In [13]:
for i, j in df.items():
    print(i)
    print(j)

day
0    1/1/2024
1    1/2/2024
2    1/3/2024
3    1/4/2024
4    1/5/2024
5    1/6/2024
Name: day, dtype: object
temperature
0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64
windspeed
0    6
1    7
2    2
3    7
4    4
5    2
Name: windspeed, dtype: int64
event
0     Rain
1    Sunny
2     Snow
3     Snow
4     Rain
5    Sunny
Name: event, dtype: object


In [14]:
for i, j in df.iterrows():
    print(i)
    print(j)

0
day            1/1/2024
temperature          32
windspeed             6
event              Rain
Name: 0, dtype: object
1
day            1/2/2024
temperature          35
windspeed             7
event             Sunny
Name: 1, dtype: object
2
day            1/3/2024
temperature          28
windspeed             2
event              Snow
Name: 2, dtype: object
3
day            1/4/2024
temperature          24
windspeed             7
event              Snow
Name: 3, dtype: object
4
day            1/5/2024
temperature          32
windspeed             4
event              Rain
Name: 4, dtype: object
5
day            1/6/2024
temperature          31
windspeed             2
event             Sunny
Name: 5, dtype: object


In [90]:
df.shape

(6, 4)

In [120]:
df.values

array([[32, '1/1/2017', 6],
       [35, '1/2/2017', 7],
       [28, '1/3/2017', 2],
       [24, '1/4/2017', 7],
       [32, '1/5/2017', 4],
       [31, '1/6/2017', 2]], dtype=object)

In [121]:
df.size

18

In [91]:
df.head()

day  temperature  windspeed  event
0  1/1/2017           32          6   Rain
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain

In [92]:
df.tail()

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow
4  1/5/2017           32          4   Rain
5  1/6/2017           31          2  Sunny

In [93]:
df[1:4]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny
2  1/3/2017           28          2   Snow
3  1/4/2017           24          7   Snow

In [94]:
df.columns

Index(['day', 'temperature', 'windspeed', 'event'], dtype='object')

In [97]:
df['temperature']

0    32
1    35
2    28
3    24
4    32
5    31
Name: temperature, dtype: int64

In [15]:
df['temperature'].mean()

np.float64(30.333333333333332)

In [16]:
df['temperature'].median()

np.float64(31.5)

In [98]:
df[['day','temperature']]

day  temperature
0  1/1/2017           32
1  1/2/2017           35
2  1/3/2017           28
3  1/4/2017           24
4  1/5/2017           32
5  1/6/2017           31

In [99]:
df['temperature'].max()

np.int64(35)

In [100]:
df['temperature'].min()

np.int64(24)

In [18]:
df['temperature'].skew()

np.float64(-0.8308251761521928)

In [101]:
df[df['temperature']>32]

day  temperature  windspeed  event
1  1/2/2017           35          7  Sunny

In [102]:
df['day'][df['temperature'] == df['temperature'].max()]

1    1/2/2017
Name: day, dtype: object

In [103]:
df['temperature'].std()

np.float64(3.8297084310253524)

In [104]:
df.describe()

temperature  windspeed
count     6.000000   6.000000
mean     30.333333   4.666667
std       3.829708   2.338090
min      24.000000   2.000000
25%      28.750000   2.500000
50%      31.500000   5.000000
75%      32.000000   6.750000
max      35.000000   7.000000

In [105]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype 
---  ------       --------------  ----- 
 0   day          6 non-null      object
 1   temperature  6 non-null      int64 
 2   windspeed    6 non-null      int64 
 3   event        6 non-null      object
dtypes: int64(2), object(2)
memory usage: 324.0+ bytes


In [109]:
df.duplicated().sum()

np.int64(0)

In [108]:
df.isnull().sum()

day            0
temperature    0
windspeed      0
event          0
dtype: int64

In [110]:
df.nunique()

day            6
temperature    5
windspeed      4
event          3
dtype: int64

In [117]:
df.reset_index(inplace=True)

In [118]:
df.set_index('event', inplace=True)
df

temperature       day  windspeed
event                                  
Rain            32  1/1/2017          6
Sunny           35  1/2/2017          7
Snow            28  1/3/2017          2
Snow            24  1/4/2017          7
Rain            32  1/5/2017          4
Sunny           31  1/6/2017          2

In [119]:
df.loc['Snow']

temperature       day  windspeed
event                                  
Snow            28  1/3/2017          2
Snow            24  1/4/2017          7

## Numpy array

In [36]:
pip install numpy

   ---------------------------------------- 0.0/12.9 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.9 MB 4.2 MB/s eta 0:00:03
   ---- ----------------------------------- 1.3/12.9 MB 4.0 MB/s eta 0:00:03
   ------ --------------------------------- 2.1/12.9 MB 3.9 MB/s eta 0:00:03
   -------- ------------------------------- 2.9/12.9 MB 4.0 MB/s eta 0:00:03
   ----------- ---------------------------- 3.7/12.9 MB 4.0 MB/s eta 0:00:03
   ------------- -------------------------- 4.5/12.9 MB 3.9 MB/s eta 0:00:03
   ---------------- ----------------------- 5.2/12.9 MB 3.9 MB/s eta 0:00:02
   ------------------ --------------------- 6.0/12.9 MB 4.0 MB/s eta 0:00:02
   ------------------- -------------------- 6.3/12.9 MB 3.5 MB/s eta 0:00:02
   --------------------- ------------------ 7.1/12.9 MB 3.8 MB/s eta 0:00:02
   ------------------------- -------------- 8.1/12.9 MB 3.8 MB/s eta 0:00:02
   ---------------------------- ----------- 9.2/12.9 MB 4.0 MB/s eta 0:00:01
   ---

  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [50]:
import numpy as np
#creating an array
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [51]:
arr2 = np.array([[1,2,3],[4,5,6]])         
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
arr2.ndim

2

In [53]:
arr3 = np.array([1, 2, 3, 4], ndmin=5)

In [54]:
# access an element(s) 
print(arr2[0])
print(arr2[0,1])

[1 2 3]
2


In [55]:
# slicing 
print(arr[1:5])
print(arr[4:])

[2 3 4 5]
[5]


In [57]:
arr4 = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])
print(arr4[1, 1:4])

[7 8 9]


In [58]:
arr.dtype

dtype('int64')

In [59]:
# data types 
arrs = np.array([1, 2, 3, 4], dtype='S')
print(arrs)
print(arrs.dtype)

[b'1' b'2' b'3' b'4']
|S1


In [61]:
arr6 = np.array([1, 0, 5])
newarr = arr6.astype(bool)
print(newarr)
print(newarr.dtype)

[ True False  True]
bool


In [62]:
# copy
x = arr.copy()
x[0] = 42
x

array([42,  2,  3,  4,  5])

In [64]:
# view
y = arr.view()
arr[0] = 42
y

array([42,  2,  3,  4,  5])

In [65]:
arre = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arre.reshape(4, 3)
newarr 

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [67]:
# flatten array 
newarr.reshape(-1)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [68]:
# iterate through each element in 2d array
for x in arr2:
  for y in x:
    print(y)

1
2
3
4
5
6


In [69]:
arrex = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
for x in np.nditer(arrex):
  print(x)

1
2
3
4
5
6
7
8


In [71]:
# with different step sizes
arrm = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
for x in np.nditer(arrm[:, ::2]):
  print(x)

1
3
5
7


In [72]:
# join two 2-D arrays along rows 
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
arr = np.concatenate((arr1, arr2), axis=1)
print(arr)

[[1 2 5 6]
 [3 4 7 8]]


In [74]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.stack((arr1, arr2), axis=1)
arr

array([[1, 4],
       [2, 5],
       [3, 6]])

In [76]:
# splitting
arr = np.array([1, 2, 3, 4, 5, 6])
newarr = np.array_split(arr, 3)
newarr

[array([1, 2]), array([3, 4]), array([5, 6])]

In [77]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])
newarr = np.hsplit(arr, 3)
newarr

[array([[ 1],
        [ 4],
        [ 7],
        [10],
        [13],
        [16]]),
 array([[ 2],
        [ 5],
        [ 8],
        [11],
        [14],
        [17]]),
 array([[ 3],
        [ 6],
        [ 9],
        [12],
        [15],
        [18]])]

In [78]:
arr = np.array([1, 2, 3, 4, 5, 4, 4])
x = np.where(arr == 4)
x

(array([3, 5, 6]),)

In [79]:
# searching through an array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
x = np.where(arr%2 == 0)
x

(array([1, 3, 5, 7]),)

In [81]:
# sort array
arr = np.array([4, 2, -1, 0, 1])
print(np.sort(arr))

[-1  0  1  2  4]
